/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg(Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KM_9028B: 'when 9028B start',
        KM_SG90_CATEGORY: 'KM_SG90',
        KM_SG90_ANGLE: 'SG90 %1 angle %2 angle',
        KM9016_HC_SR04_READ_DISTANCE: 'ultrasonic %1 read distance %2',
        BUTTON: 'button %1 %2 key press?',
        YELLOW_BUTTON: 'yellow button %1 press?',
        COLLIDE: 'collide switch %1 colliding',
        KM_MI: 'sound sensor %1 value',
        KM_RAY: 'ray %1 value',
        KM_IRRX: ' Infrared reception %1 data',
        KM_IRAVOID: 'infrared avoid %1 barrier?',
        KM_IRLINE: 'Follow the trail %1 %2 status %3',
        KM_COLOR: 'init color sensor %1',
        KM_COLOR_READ: 'read color sensor pin %1 color %2',
        KM_RP: 'potentiometer %1 value',
        KM_MOTOR: 'set motor %1 speed(1-10) %2 direction %3',
        DHT11: 'pin %1 read %2',
        KM_TOP_ACC: 'fetch top pin %1 dir %2 axis %3',
        KM_RGB_INIT: 'RGB init pin %1',
        KM_RGB_BRIGHT: 'RGB pin %1 bright(0-255) %2',
        KM_RGB_SETPIXELCOLOR: 'RGB pin %1 the %2 LED color %3',
        KM_RGB_CLOSE: 'RGB pin %1 close',
        KM_BUZZER: 'play %1 passage %2 frequency %3 delay %4 millisecond',
        KM_BUZZER_CLOSE: 'stop %1 passage %2',
        KM_CLOCKDISPLAY_CATEGORY: '4-Digit Clock Display',
        KM_CLOCKDISPLAY_INIT: 'init 4-digit clock display pin %1',
        KM_CLOCKDISPLAY_SETBRIGHTNESS: 'set 4-digit clock display brightness %1',
        KM_CLOCKDISPLAY_DISPLAYNUMBER: '4-digit clock display show number %1',
        KM_CLOCKDISPLAY_DISPLAYSTRING: '4-digit clock display show string %1',
        KM_CLOCKDISPLAY_DISPLAY: '4-digit clock display show %1 at bit %2',
        KM_CLOCKDISPLAY_SETPOINT: '4-digit clock display set point %1',
        KM_CLOCKDISPLAY_STATE_ON: 'on',
        KM_CLOCKDISPLAY_STATE_OFF: 'off',
        KM_CLOCKDISPLAY_SETPOINT_TOOLTIP: 'It will take effect after the next update of the display.',
        KM_CLOCKDISPLAY_CLEAR: 'clear 4-digit clock display',
        KM_ROCKER: 'rocker pin %1 %2 value',
        MP3_VOLUM: 'MP3 pin %1 volum(0-30%) %2',
        MP3_SELECT: 'MP3 pin %1 play track %2',
        MP3_CONTROL: 'MP3 pin %1 play control %2',
        MP3_MODE: 'MP3 pin %1 play mode %2',
        MP3_NUMBER: 'MP3 pin %1 play distance %2 cm',
        LED: 'LED pin %1 state %2',
        LED_COLOR: 'Three-color lights pin %1 green %2 yellow %3 red %4',
        MATRIX_BRIGHT: 'martx pin %1 setbrightness(0-15) %2',
        MATRIX_ROTATION: 'martx pin %1 roattion %2',
        MATRIX_BITMAP: 'martx pin %1 default pattern %2',
        MATRIX_CHAR: 'martx pin %1 display char %2',
        MATRIX_TEXT: 'martx pin %1 display %2 delay %3',
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KM_9028B: '当9028B启动',
        KM_SG90_CATEGORY: '舵机',
        KM_SG90_ANGLE: '舵机 %1 旋转 %2 度',
        KM9016_HC_SR04_READ_DISTANCE: '超声波传感器 %1 读取距离 %2',
        BUTTON: '按键 %1 %2键被按下？',
        YELLOW_BUTTON: '黄色按钮 %1 被按下?',
        COLLIDE: '碰撞开关 %1 碰到物体',
        KM_MI: '声音传感器 %1 数值',
        KM_RAY: '光线传感器 %1 数值',
        KM_IRRX: ' 红外接收 %1 数据',
        KM_IRAVOID: '红外避障 %1 检测到障碍?',
        KM_COLOR: '初始化颜色传感器 %1',
        KM_COLOR_READ: '读取颜色传感器端口 %1 颜色 %2',
        KM_RP: '电位器 %1 数值',
        KM_MOTOR: '设置电机 %1 速度(1-10) %2 方向 %3',
        DHT11: '端口 %1 读取 %2',
        KM_IRLINE: '循迹模块 %1 %2 状态 %3',
        KM_TOP_ACC: '获取陀螺仪 端口 %1 %2 轴 %3',
        KM_RGB_INIT: '初始化RGB 端口 %1',
        KM_RGB_BRIGHT: 'RGB 端口 %1 亮度设置为(0-255) %2',
        KM_RGB_SETPIXELCOLOR: 'RGB彩灯 端口 %1 第 %2 个灯颜色为 %3',
        KM_RGB_CLOSE: 'RGB彩灯 端口 %1 全部熄灭',
        KM_BUZZER: '播放声音 %1 通道 %2 频率 %3 延时 %4 毫秒',
        KM_BUZZER_CLOSE: '结束声音 %1 通道 %2',
        KM_CLOCKDISPLAY_CATEGORY: '4位时钟数码管',
        KM_CLOCKDISPLAY_INIT: '初始化4位时钟数码管 %1',
        KM_CLOCKDISPLAY_SETBRIGHTNESS: '设置4位时钟数码管亮度 %1',
        KM_CLOCKDISPLAY_DISPLAYNUMBER: '4位时钟数码管显示数字 %1',
        KM_CLOCKDISPLAY_DISPLAYSTRING: '4位时钟数码管显示字符 %1',
        KM_CLOCKDISPLAY_DISPLAY: '4位时钟数码管显示 %1 第 %2 位',
        KM_CLOCKDISPLAY_SETPOINT: '4位时钟数码管设置点 %1',
        KM_CLOCKDISPLAY_STATE_ON: '开',
        KM_CLOCKDISPLAY_STATE_OFF: '关',
        KM_CLOCKDISPLAY_SETPOINT_TOOLTIP: '将在下次更新显示后生效.',
        KM_CLOCKDISPLAY_CLEAR: '清空4位时钟数码管',
        KM_ROCKER: '摇杆 端口 %1 %2 值',
        MP3_VOLUM: 'MP3 端口 %1 音量(0-30%) %2',
        MP3_SELECT: 'MP3 端口 %1 播放曲目 %2',
        MP3_CONTROL: 'MP3 端口 %1 播放控制 %2',
        MP3_MODE: 'MP3 端口 %1 播放模式 %2',
        MP3_NUMBER: 'MP3 端口 %1 播放距离 %2 cm',
        LED: '单色灯 端口 %1 状态 %2',
        LED_COLOR: '三色灯 端口 %1 绿色 %2 黄色 %3 红色 %4',
        MATRIX_BRIGHT: '点阵屏 端口 %1 设置亮度(0-15) %2',
        MATRIX_ROTATION: '点阵屏 端口 %1 旋转 %2',
        MATRIX_BITMAP: '点阵屏 端口 %1 预设图案 %2',
        MATRIX_CHAR: '点阵屏 端口 %1 显示字符 %2',
        MATRIX_TEXT: '点阵屏 端口 %1 显示字符串 %2 延时 %3',
    });
    return Blockly;
}

exports = addMsg;